// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe6ZHxqXPZ1Unj0xzkxCbEX9NysH1nOic',
    appId: '1:363964507923:web:bab6835ff54859f6495ce6',
    messagingSenderId: '363964507923',
    projectId: 'guided-bcd34',
    authDomain: 'guided-bcd34.firebaseapp.com',
    storageBucket: 'guided-bcd34.appspot.com',
    measurementId: 'G-DHHRBTQDPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYFd1sPXK16U5xSO7GTZLiI3ovG507Y8U',
    appId: '1:363964507923:android:7485e354fd9654ba495ce6',
    messagingSenderId: '363964507923',
    projectId: 'guided-bcd34',
    storageBucket: 'guided-bcd34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmBZgCKIWuLtTDwVfyvuLKnp4N15P1Swc',
    appId: '1:363964507923:ios:93181df40488178f495ce6',
    messagingSenderId: '363964507923',
    projectId: 'guided-bcd34',
    storageBucket: 'guided-bcd34.appspot.com',
    iosBundleId: 'com.zikrulloh.guidist',
  );
}
